### ISSUE TITLE
Initial deploy fails due to S3 ACL issues.

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/aws-lambda-nextjs#4]
***This is an outstanding contribution and seriously needed by those having problems with amplify and other versions (mostly related to SSR + Auth).  I hope it continues to be supported as a standalone deploy method.

**Demo**
Specify the name of the demo that you encountered the bug.

Running the CDK version

**Describe the bug**
What is the problem? A clear and concise description of the bug.

Initial deploy raises this error--> "Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting "

**Expected behavior**

Complete, correct build

**Current behavior**
What actually happened? 

Status code: 400, invalid bucket acl with object ownership

Please include full errors, uncaught exceptions, stack traces, and relevant logs.

NextjsLambdaCdkStack: creating CloudFormation changeset...
9:17:05 AM | CREATE_FAILED        | AWS::S3::Bucket                                 | nextloggingbucket5D8161B
3
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Cod
e: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: 1SRSBAH38WENG4WQ; S3 Extended Request ID:
ihKstTh0QSFxv/xo1BXJTK5HnJioO7+7b9Ct82JFY8SNHtPfmNOaeenN6i0sz/V9RVuxgf0Yvi8=; Proxy: null)

 ❌  NextjsLambdaCdkStack failed: Error: The stack named NextjsLambdaCdkStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: 1SRSBAH38WENG4WQ; S3 Extended Request ID: ihKstTh0QSFxv/xo1BXJTK5HnJioO7+7b9Ct82JFY8SNHtPfmNOaeenN6i0sz/V9RVuxgf0Yvi8=; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/home/vfulco/.nvm/versions/node/v18.13.0/lib/node_modules/aws-cdk/lib/index.js:380:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/home/vfulco/.nvm/versions/node/v18.13.0/lib/node_modules/aws-cdk/lib/index.js:383:145458)
    at async /home/vfulco/.nvm/versions/node/v18.13.0/lib/node_modules/aws-cdk/lib/index.js:383:128776
    at async run (/home/vfulco/.nvm/versions/node/v18.13.0/lib/node_modules/aws-cdk/lib/index.js:383:126782)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named NextjsLambdaCdkStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: 1SRSBAH38WENG4WQ; S3 Extended Request ID: ihKstTh0QSFxv/xo1BXJTK5HnJioO7+7b9Ct82JFY8SNHtPfmNOaeenN6i0sz/V9RVuxgf0Yvi8=; Proxy: null)
    at deployStacks (/home/vfulco/.nvm/versions/node/v18.13.0/lib/node_modules/aws-cdk/lib/index.js:383:129083)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/home/vfulco/.nvm/versions/node/v18.13.0/lib/node_modules/aws-cdk/lib/index.js:383:147507)
    at async exec4 (/home/vfulco/.nvm/versions/node/v18.13.0/lib/node_modules/aws-cdk/lib/index.js:438:51799)

Stack Deployments Failed: Error: The stack named NextjsLambdaCdkStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: 1SRSBAH38WENG4WQ; S3 Extended Request ID: ihKstTh0QSFxv/xo1BXJTK5HnJioO7+7b9Ct82JFY8SNHtPfmNOaeenN6i0sz/V9RVuxgf0Yvi8=; Proxy: null)

**To Reproduce**
Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
For more complex issues provide a repo with the smallest sample that reproduces the bug.
        
Avoid including business logic or unrelated code, it makes diagnosis more difficult.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubuntu 22.04
 - Browser [e.g. chrome, safari] chrome Version 112.0.5615.165 
 - Version [e.g. 22] 22.04
--CDK 2.30.0

**Additional context**

**Comment by coderaim** [comment]
@weisisheng 
Check  objectOwnership attribute in cdk script and set it to OBJECT_WRITER.
Default will be BucketOwnerEnforced which won't allow to set acl's

**Comment by weisisheng** [comment]
Awesome!  That did it.  Thanks.

**Comment by coderaim** [comment]
Glad to contribute in the community 😃
