### ISSUE TITLE
Server error with first deploy

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/aws-lambda-nextjs#5]
**Demo**
Specify the name of the demo that you encountered the bug.

aws-lambda-nextjs, sam version

**Describe the bug**
What is the problem? A clear and concise description of the bug.

first attempt to access website on cloudfront raises error

**Expected behavior**

rendering standard next.js home page

**Current behavior**
What actually happened? 

Website shows, ' {"message": "Internal server error"} '

Digging in to cloudwatch logs shows, " 2023-04-26T09:42:44.776+07:00CopyTypeError: handler is not a function | TypeError: handler is not a function "

Please include full errors, uncaught exceptions, stack traces, and relevant logs.

**To Reproduce**
Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
For more complex issues provide a repo with the smallest sample that reproduces the bug.

1/ Fix ACL issue with:

      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter 

in two buckets

2/ sam validate && sam build && sam deploy --guided --region foo --profile foo2

3/ give custom bucket name
Stack deploys successfully.
        
Avoid including business logic or unrelated code, it makes diagnosis more difficult.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] chrome 112.0
 - Version [e.g. 22] 22.04

**Additional context**

**Comment by kachkaev** [comment]
What version of Next.js is it @weisisheng?

**Comment by weisisheng** [comment]
Sorry for the delay, should have mentioned 12.2.x

**Comment by stevenlafl** [comment]
For me it appears to be isolated to POST requests.

**Comment by stevenlafl** [comment]
@weisisheng I figured it out, at least my case.. The default timeout is 3 seconds. It needs to be way higher.

**Comment by weisisheng** [comment]
Great.  Will use this.
